### ISSUE TITLE
Establish meeting time and first date

### ISSUE THREAD

**Issue by gmcerveny** [GeekdomSA/bookclub#1]
**Suggested date:** Thursday, January 10

**Suggested time:** ?? Aaron ??

**Comment by wwkeyboard** [comment]
6 sounds good to me. However I'll have to leave at 7 for other Thursday night commitments.

I like the idea of reading the Dynamo paper. It's kind of long, but well written for a research paper. http://www.read.seas.harvard.edu/~kohler/class/cs239-w08/decandia07dynamo.pdf

**Comment by gmcerveny** [comment]
We'll do Thursdays starting January 10th, 6-7pm.  

I just created a wiki and added this article to it.
