### ISSUE TITLE
Integrated Tests are a Scam

### ISSUE THREAD

**Issue by warmwaffles** [GeekdomSA/bookclub#16]
http://www.jbrains.ca/permalink/integrated-tests-are-a-scam-part-1

**Comment by wwkeyboard** [comment]
He's link-baiting by playing with semantics. What most people talk about integration, or in his edit 'integrated', tests they are referring to contract tests and specification verification. While there is a strong argument against testing arbitrary subsets of your application, they mostly don't apply to validations of your entire application.

This is why I'm leery of papers and blog posts by consultants. Sometimes their aim is to share information, sometimes it's to drive linkes to their site, thereby increasing their (mind|google)share.

**Comment by warmwaffles** [comment]
> This is why I'm leery of papers and blog posts by consultants. Sometimes their aim is to share information, sometimes it's to drive linkes to their site, thereby increasing their (mind|google)share.

But it is still good to know, for the sake of knowing. You see his argument and you have structured your counter argument. To me, that shows that this article was a good choice for you.

I think Integrated Tests are brittle and prone to break often. However, I do think they are still necessary towards the end of a development cycle. When the integration tests involve capybara and testing outside in, if the UI changes, that will affect the integration test or (acceptance test if you will).
