### ISSUE TITLE
I couldn't really learn Erlang, 'cos it didn't exist, so I invented it.

### ISSUE THREAD

**Issue by gmcerveny** [GeekdomSA/bookclub#17]
http://erlang.org/pipermail/erlang-questions/2013-January/071949.html

**Comment by wwkeyboard** [comment]
You've got to include "Erlang: The Movie" with that http://www.youtube.com/watch?v=xrIjfIjssLE

**Comment by cwollak** [comment]
I'm not sure why I just watched that whole video...

-Cole
