### ISSUE TITLE
Game design concept extra meta for you

### ISSUE THREAD

**Issue by warmwaffles** [GeekdomSA/bookclub#18]
I just found these videos and I really like this persons approach to explaining concepts behind some design decisions with regards to games. I feel it's applicable to any type of development. Games are what inspire me to program.

http://www.youtube.com/user/ExtraCreditz
- [Balancing for Skill](http://www.youtube.com/watch?v=EitZRLt2G3w)
- [Counter Play](http://www.youtube.com/watch?v=BRBcjsOt0_g)
- [Power Creep](http://www.youtube.com/watch?v=Bxszx60ZwGw)
- [Perfect Imbalance](http://www.youtube.com/watch?v=e31OSVZF77w)

These are all about design and are very thought provoking.

**Comment by richardjortega** [comment]
I think people don't give video games the credit they deserve, a well thought game that is balanced and fun for all is a masterpiece. I compare a lot to what I do to video games, hell I use the analogies all the time. It's amazing that great games can keep the vision, focus, and creativity along with the implementation on a nice track until the game is released.

Didn't know about these videos, much appreciated.

**Comment by warmwaffles** [comment]
Yes, I looked at these also as a way to program your users.
