### ISSUE TITLE
Conference Room Reservations?

### ISSUE THREAD

**Issue by AngelMarquez** [GeekdomSA/bookclub#19]
Just a quick issue: I just checked conference room reservations ( http://goo.gl/XiadN ) and far as I can tell the system isn't used at all. Am I just looking in the wrong place? Or have we not reserved the room?

**Comment by gmcerveny** [comment]
We're supposed to be doing that.  I find the manual process of reserving one night at a time cumbersome.

**Comment by gmcerveny** [comment]
Updated through the month of February.
