### ISSUE TITLE
Move Meeting to !Thursday

### ISSUE THREAD

**Issue by gmcerveny** [GeekdomSA/bookclub#20]
We'd like to allow bookclub to move to a new night so members (_cough_ @wwkeyboard ) can hang out longer and move to informal discussions and coding sessions.

**Comment by nroach** [comment]
The motion is seconded and proposed to be put forth for discussion prior to a vote.

**Comment by warmwaffles** [comment]
A better time frame would be nice too.

**Comment by gmcerveny** [comment]
@warmwaffles what time frame do you want?

**Comment by warmwaffles** [comment]
I think this could be a good lunch get together

**Comment by AngelMarquez** [comment]
Nay! Some of us have day jobs that preclude lunch from ever being a realistic option.

**Comment by nroach** [comment]
They don't let you have lunch?  That's cold. :)

Nathan

**Comment by wwkeyboard** [comment]
I also vote against lunchtime.

**Comment by AngelMarquez** [comment]
@nroach That'll teach me to proofread what I write. 

My vote is for Tuesday nights.

While Monday, Tuesday, and most Wednesday nights work well for me the first Wednesday of every month is the "San Antonio Hackers Association" meeting from 6-9. I played a small role in getting those meetings moved to Geekdom and I really enjoy attending them so I'd likely miss book club those days.

Regardless of the day of the week we decide on,  I'll set up a "Programming Night" event immediately after the meeting. Hopefully it could be merged or at least coexist with the iOS programming night so we can start forming some bonds among developers at Geekdom.

**Comment by gmcerveny** [comment]
Meeting going forward is now Tuesdays.
