### ISSUE TITLE
Choose next articles

### ISSUE THREAD

**Issue by gmcerveny** [GeekdomSA/bookclub#21]
@AngelMarquez is responsible

**Comment by AngelMarquez** [comment]
Here we go. Can you spot the theme? 

http://tomayko.com/writings/rest-to-my-wife
http://whyjava.wordpress.com/2011/08/04/how-i-explained-mapreduce-to-my-wife/
http://www.codinghorror.com/blog/2012/03/rubber-duck-problem-solving.html
http://programmers.blogoverflow.com/2012/08/20-controversial-programming-opinions/
