### ISSUE TITLE
Next book to read

### ISSUE THREAD

**Issue by wwkeyboard** [GeekdomSA/bookclub#28]
We are about to finish Clean Code, so we need to pick our next book. I've heard suggestions for books on Agile and Testing.

My vote is for Growing Object-Oriented Software, Guided by Tests: http://www.amazon.com/Growing-Object-Oriented-Software-Guided-Tests/dp/0321503627

**Comment by warmwaffles** [comment]
This book sounds interesting. Though @gmcerveny doesn't test too much

**Comment by gmcerveny** [comment]
I'm down as long as isn't called dodecahedronal testing

**Comment by gmcerveny** [comment]
Last night we voted on 7 languages in 7 weeks.

**Comment by chriscavin** [comment]
.... but we're really doing 7 Languages in 14 Weeks, right?

**Comment by warmwaffles** [comment]
![aww yea](http://i.imgur.com/70Hw0c3.jpg)
