### ISSUE TITLE
CAP Theorem 

### ISSUE THREAD

**Issue by nathannis** [GeekdomSA/bookclub#29]
These 2 are the articles that I would like to discuss:
http://www.allthingsdistributed.com/2007/12/eventually_consistent.html
http://www.allthingsdistributed.com/2008/12/eventually_consistent.html

What is CAP Theorem?
Wiki - http://en.wikipedia.org/wiki/CAP_theorem
Another introduction
http://www.julianbrowne.com/article/viewer/brewers-cap-theorem
A fun little anecdote to get introduced to CAP.
http://ksat.me/a-plain-english-introduction-to-cap-theorem/

**Comment by gmcerveny** [comment]
Added to repo, thanks!
https://github.com/GeekdomSA/bookclub/tree/master/2013/04/17
