### ISSUE TITLE
Choose first book, divide reading, and schedule

### ISSUE THREAD

**Issue by gmcerveny** [GeekdomSA/bookclub#3]

**Comment by wwkeyboard** [comment]
Matt suggested " Clean Code: A Handbook of Agile Software Craftsmanship" by Robert C. Martin. I agree this would be a great first book, as long as you don't get the Kindle version. Supposedly the code samples are all screwed up. Given the need to run down the book itself, I think the first two chapters would be sufficient reading for the 17th. This covers the introduction and Meaningful names.

Derp, I'll edit the project.

**Comment by cwollak** [comment]
Sweet!!!

I'll pick it up.

Sent from my iPhone

On Jan 7, 2013, at 6:29 AM, Aaron Lee notifications@github.com wrote:

Matt suggested " Clean Code: A Handbook of Agile Software Craftsmanship" by
Robert C. Martin. I agree this would be a great first book, as long as you
don't get the Kindle version. Supposedly the code samples are all screwed
up. Given the need to run down the book itself, I think the first two
chapters would be sufficient reading for the 17th. This covers the
introduction and Meaningful names.

—
Reply to this email directly or view it on
GitHubhttps://github.com/GeekdomSA/bookclub/issues/3#issuecomment-11949934.
