### ISSUE TITLE
Hexagonal rails

### ISSUE THREAD

**Issue by warmwaffles** [GeekdomSA/bookclub#7]
http://www.confreaks.com/videos/977-goruco2012-hexagonal-rails

http://blog.mattwynne.net/category/hexagonal-rails/

http://www.infoq.com/interviews/wynne-bdd

**Comment by wwkeyboard** [comment]
I don't know how to vote on these, but +1 LGTM sounds like a winner.

**Comment by gmcerveny** [comment]
rails dorks, whatever, i'll learn some new buzzwords

**Comment by warmwaffles** [comment]
Well he does have a point when he says "I call it hexagonal rails because it sounds better than adapters and ports rails"
