### ISSUE TITLE
Robert Martin: Architecture the Lost Years

### ISSUE THREAD

**Issue by warmwaffles** [GeekdomSA/bookclub#8]
GREAT video.

http://www.confreaks.com/videos/759-rubymidwest2011-keynote-architecture-the-lost-years

**Comment by gmcerveny** [comment]
This looks good to me for the next article session.

**Comment by warmwaffles** [comment]
Could assign it as something to watch and take notes on, and come to the next meeting prepared to discuss

**Comment by sundip** [comment]
Deferring DB off, very interesting.

**Comment by warmwaffles** [comment]
Yes it is. If you use Ruby, go take a look at the `gem virtus`. I use it all the time. It's a great supplement until I feel the need to have the data in a database.
